### PR TITLE
Bootstrap website

### PR DESCRIPTION
**Pull request by RemiClouet**

### CODE REVIEW

**Comment by Croydon** [comment]
In general it is better to make many small commits instead of one monster commit like this :)
Small commits make it easier to review changes

**Comment by RemiClouet** [comment]
Well, pretty much everything is changed. I could upload the files 1by1 but those are linked with each others, not sure it would help the review.

**Comment by Croydon** [comment]
I suppose the people of RE will manage that. Just a general note :)

**Comment by qreeves** [comment]
What do I need to know/do before I make it live?

**Comment by RemiClouet** [comment]
well, should be working as it is. will just need to redo the galery php script with a "item active" class on 1rst slide

**Pull request merged**
